# Generated by Django 2.0.2 on 2018-02-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.TextField()),
                ('student_id', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('guardian_id', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.AccountType')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Schools')),
            ],
        ),
    ]
