# Generated by Django 2.0.2 on 2018-02-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180224_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
