# Generated by Django 2.0.2 on 2018-02-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_users_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='dob',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
    ]
