# Generated by Django 2.0.2 on 2018-02-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_users_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='category',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='classes',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
    ]
