# Generated by Django 2.0.2 on 2018-02-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20180224_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
